[workspace]
# Use the latest resolver available
resolver = "3"
# Include both parts of the library in the workspace
members = [
    "deboa",
    "deboa-bora",
    "deboa-extras",
    "deboa-fory", 
    "deboa-macros",
    "examples/blog", 
    "examples/chat", 
    "examples/postman", 
    "examples/catcher",
    "examples/sse", 
    "examples/simple", 
    "vamo", 
    "vamo-macros", 
]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z" 
lto = true
codegen-units = 1
panic = "abort"
