[package]
name = "deboa-macros"
edition = "2021"
version = "0.0.1"
authors = ["Rogerio Ara√∫jo <rogerio.araujo@gmail.com>"]
description = "macros for deboa"
license = "MIT"
repository = "https://github.com/ararog/deboa"
readme = "README.md"
keywords = ["compiler-plugin"]
exclude = [".travis.yml"]
publish = true
rust-version = "1.64.0"


[features]
default = ["json"]
json = ["deboa-extras/json"]
xml = ["deboa-extras/xml"]
msgpack = ["deboa-extras/msgpack"]

[dependencies]
deboa = { path = "../deboa", version = "0.0.5", features = ["http1"] }
deboa-bora = { path = "../deboa-bora", version = "0.0.2" }
deboa-extras = { path = "../deboa-extras", version = "0.0.1", features = ["json"] }
tokio = { version = "1.47.1", features = ["full"] }
serde = "1.0.219"

[dev-dependencies]
deboa-tests = { path = "../deboa-tests", version = "0.0.1" }
httpmock = { version = "0.8.0-alpha.1", features = ["http2"] }
tokio = "1.47.1"

